### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by shreya024** [NegiAkash890/editor-frontend#1]
I would like to work on the issue of adding a Splash screen with the logo. Kindly assign

**Comment by NegiAkash890** [comment]
Hi @shreya024 that would be great I hope that you have successfully setup the project locally if not you can refer the README. Let me know if you face any issue.

**Comment by shreya024** [comment]
> Hi @shreya024 that would be great I hope that you have successfully setup the project locally if not you can refer the README. Let me know if you face any issue.

Yes, I have successfully setup the project. Thank you for assigning, I am working on the issue :)
