### ISSUE TITLE
Adding Feature of Code Highlighting 

### ISSUE THREAD

**Issue by ManavSarkar** [NegiAkash890/editor-frontend#11]
Code Highlighting is a very important feature of a good IDE. There are lots of code highlighters that can be integrated here.

**Comment by NegiAkash890** [comment]
Can you share some examples ?

**Comment by ManavSarkar** [comment]
Sorry for the late reply. I was on some other project. Hope you don't mind.
I have some links here that work as a 

1. [Ace](https://ace.c9.io/#nav=embedding)
2. [Monaco](https://microsoft.github.io/monaco-editor/)
3. [EditArea](https://www.cdolivet.com/editarea/)

code editor and work seamlessly.
I have an example of the Ace code editor that I integrated into a normal Node js site. It has also auto code completion.
![60](https://user-images.githubusercontent.com/42129636/144753536-53c65040-8c11-42b4-923e-353fbcd16e17.gif)

Thank you

**Comment by NegiAkash890** [comment]
Hi @ManavSarkar . We already have a dependency in package.json [react-syntax-highlighter](https://github.com/NegiAkash890/editor-frontend/blob/7286664237930f337c6861f215cea4e5538ffbc4/package.json#L20) . Let me know if you can do something with that or else you can do it the way you are planning.

**Comment by NegiAkash890** [comment]
> Sorry for the late reply. I was on some other project. Hope you don't mind. I have some links here that work as a
> 
>     1. [Ace](https://ace.c9.io/#nav=embedding)
> 
>     2. [Monaco](https://microsoft.github.io/monaco-editor/)
> 
>     3. [EditArea](https://www.cdolivet.com/editarea/)
> 
> 
> code editor and work seamlessly. I have an example of the Ace code editor that I integrated into a normal Node js site. It has also auto code completion. ![60](https://user-images.githubusercontent.com/42129636/144753536-53c65040-8c11-42b4-923e-353fbcd16e17.gif)
> 
> Thank you

Any updates so far ?

**Comment by aakankshabhende** [comment]
Any update? @ManavSarkar

**Comment by Rishi-121** [comment]
Can I work on this feature?

**Comment by NegiAkash890** [comment]
> Can I work on this feature?

Yea sure assigning you this issue.

**Comment by Rishi-121** [comment]
Added the feature...just check the pull request from dev-branch.

Hope you will like it, 😊

PR #27

**Comment by NegiAkash890** [comment]
Closed by #29
