### ISSUE TITLE
Editor clears previous value on changing language

### ISSUE THREAD

**Issue by MitanshiKshatriya** [NegiAkash890/editor-frontend#12]
Currently, on changing the language, the code stays the same. I think it would be a better experience if we could refresh the code as well on changing language and also making a small prompt warning editor values would be replaced.

**Comment by kanthalaHarivardhanReddy** [comment]
Assign me! I would like to work on this issue.

**Comment by NegiAkash890** [comment]
I think i can be done as a part of #4 @MitanshiKshatriya . Let me know what you think?

**Comment by NegiAkash890** [comment]
> Assign me! I would like to work on this issue.

Hi @kanthalaHarivardhanReddy in the meantime since this issue is already under work you can look for some other issue to work on ;)

**Comment by MitanshiKshatriya** [comment]
@NegiAkash890 yes that would be better

**Comment by kanthalaHarivardhanReddy** [comment]
ok fine. I got it

**Comment by NegiAkash890** [comment]
Closing as this can be done as a part of #4
