### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by shreya024** [NegiAkash890/editor-frontend#13]
I would like to work on the issue of making this app into a Progressive Web Application.
@NegiAkash890 Kindly assign

**Comment by NegiAkash890** [comment]
Hi @shreya024 that a nice idea but at this point our focus should on making theIDE as accessible and user-friendly as possible. Things like snippets functionalities ( drag/drop), upload code should be priority, download option. Once these are added we can think of making it a PWA.

**Comment by shreya024** [comment]
> Hi @shreya024 that a nice idea but at this point our focus should on making theIDE as accessible and user-friendly as possible. Things like snippets functionalities ( drag/drop), upload code should be priority, download option. Once these are added we can think of making it a PWA.

Okay cool
