### ISSUE TITLE
when clear button is clicked the message "console cleared" should disappear after some time

### ISSUE THREAD

**Issue by kanthalaHarivardhanReddy** [NegiAkash890/editor-frontend#14]
when we click on the clear button the "console cleared" is appeared in the output box.
so, It will be better if the message is also cleared after some seconds

**Comment by kanthalaHarivardhanReddy** [comment]
kindly assign it to me!!

**Comment by NegiAkash890** [comment]
hi @kanthalaHarivardhanReddy I think this is not needed.

**Comment by kanthalaHarivardhanReddy** [comment]
Ok @NegiAkash890 I'm closing it
