### ISSUE TITLE
Redesign UI

### ISSUE THREAD

**Issue by akshat-kumar2109** [NegiAkash890/editor-frontend#2]
I would like to make my contribution by redesigning the UI. Please assign me this issue.

**Comment by NegiAkash890** [comment]
Hi @akshat-kumar2109 you can go ahead.

**Comment by LegendSumeet** [comment]
great one @akshat-kumar2109 i am mentor of these project any issue you can reach to me.

**Comment by akshat-kumar2109** [comment]
@LegendSumeet Sure sir!

**Comment by NegiAkash890** [comment]
> I would like to make my contribution by redesigning the UI. Please assign me this issue.

Any updates ?

**Comment by akshat-kumar2109** [comment]
There was an issue. My laptop broke. So i have to buy a new one. That's why it is delayed. Just give me some time.

**Comment by NegiAkash890** [comment]
Closing this issue @akshat-kumar2109. Whenever your issue is resolved you can open the issue again.
