### ISSUE TITLE
If console is already cleared then clear button is hidden

### ISSUE THREAD

**Issue by kanthalaHarivardhanReddy** [NegiAkash890/editor-frontend#20]
SWOC 2.0

**Comment by NegiAkash890** [comment]
That can be done !

**Comment by kanthalaHarivardhanReddy** [comment]
I'm working on it!

**Comment by aakankshabhende** [comment]
Any updates? @kanthalaHarivardhanReddy

**Comment by kanthalaHarivardhanReddy** [comment]
Hey @aakankshabhende,
I will be making a pull request by this weekend.

**Comment by aakankshabhende** [comment]
Okay no issues :) @kanthalaHarivardhanReddy

**Comment by Rishi-121** [comment]
I would like to work on this issue...@aakankshabhende

**Comment by Rishi-121** [comment]
I have resolved this issue. 

Check the PR, 

#28

**Comment by Rishi-121** [comment]
This issue is fixed. Please, check the production version...or let me know is there any more to add.

@aakankshabhende

**Comment by Rishi-121** [comment]
This issue is also resolved @NegiAkash890 

Check the output console, the button is not visible if there is not output.

**Comment by NegiAkash890** [comment]
Fixed with #29
