### ISSUE TITLE
Feature: Upload file

### ISSUE THREAD

**Issue by shreya024** [NegiAkash890/editor-frontend#21]
The user can upload a file and the code inside the file will be transferred to the IDE where he/she can then edit or run the program.
@NegiAkash890 Kindly Assign me this issue.

**Comment by shreya024** [comment]
I have the code ready for this issue. But I am getting these two errors while doing npm install after cloning.Kindly help me resolve them
![20211208_080436](https://user-images.githubusercontent.com/72400676/145144782-9f1f0416-6cc5-4e31-b2d0-eeab60294d96.jpg)
![20211208_081936](https://user-images.githubusercontent.com/72400676/145144818-85e2239e-9d44-4e5d-b79e-3a1c4b602c78.jpg)

**Comment by NegiAkash890** [comment]
Just remove `11` from line 27520 in package.json

**Comment by shreya024** [comment]
> Just remove `11` from line 27520 in package-lock.json

Okay thank you. I have made the PR :)

**Comment by shreya024** [comment]
@NegiAkash890 Kindly add SWOC label :)

**Comment by shreya024** [comment]
@NegiAkash890 Kindly update my scores in the SWOC scoresheet

**Comment by NegiAkash890** [comment]
> @NegiAkash890 Kindly update my scores in the SWOC scoresheet

Please, share your PID along with the merge request

**Comment by shreya024** [comment]
> > @NegiAkash890 Kindly update my scores in the SWOC scoresheet
> 
> Please, share your PID along with the merge request

My PID is 921 and merged PRs are #22 and #25
