### ISSUE TITLE
Feature:Download File

### ISSUE THREAD

**Issue by shreya024** [NegiAkash890/editor-frontend#23]
The user can download the current code in the IDE as .txt file on their system

@NegiAkash890 Kindly assign

**Comment by LegendSumeet** [comment]
@NegiAkash890 assign her to these issue....
and @shreya024 do in that way the user can download the file with extension i.e, .java , .cpp , etc not in text file

**Comment by NegiAkash890** [comment]
Ok! You can start working on this one.

**Comment by NegiAkash890** [comment]
Thanks @shreya024 your PR has been merged. Nice work so far : ) .

**Comment by shreya024** [comment]
> Thanks @shreya024 your PR has been merged. Nice work so far : ) .

Thank you :)
