### ISSUE TITLE
Feature: Starter Template

### ISSUE THREAD

**Issue by abaran803** [NegiAkash890/editor-frontend#24]
Hi @NegiAkash890 , I want to add a feature that provides a starter template for all languages when opening the site or switching between languages.

**Comment by aakankshabhende** [comment]
Starter template of language specified by the user? @abaran803

**Comment by abaran803** [comment]
> Starter template of language specified by the user? @abaran803 I guess this issue is similar to #4

I didn't see that. Is there anything else for students like me(beginner)?

**Comment by NegiAkash890** [comment]
> > Starter template of language specified by the user? @abaran803 I guess this issue is similar to #4
> 
> I didn't see that. Is there anything else for students like me(beginner)?

Hi, @abaran803 there are many things that you can work on For Eg: we can have snippets that can be used in code.

**Comment by abaran803** [comment]
> > > Starter template of language specified by the user? @abaran803 I guess this issue is similar to #4
> > 
> > 
> > I didn't see that. Is there anything else for students like me(beginner)?
> 
> Hi, @abaran803 there are many things that you can work on For Eg: we can have snippets that can be used in code.

Yeah @NegiAkash890, I also thought about snippets, but the problem is that different people use different snippets. And, if I want to provide user-defined snippets, then for different users, the different snippets will be shown. But this requires login to save and separate the snippets.

**Comment by NegiAkash890** [comment]
> 

That's not what I am talking about. Like generic syntax for loop, while loop etc.

**Comment by abaran803** [comment]
> > 
> 
> That's not what I am talking about. Like generic syntax for loop, while loop etc.

Ok

**Comment by Rishi-121** [comment]
@NegiAkash890 this issue is also resolved

**Comment by abaran803** [comment]
> @NegiAkash890 this issue is also resolved
> 
> Thanks to @arp99
> 
> Check #26

Ok, then please close this issue. I'm not able to do anything due to my ongoing semester exams.
