### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by Deepak-Kumar201** [NegiAkash890/editor-frontend#3]
Sir I would like to work on auto-completion of brackets and auto indentation. Please assign me this issue.

**Comment by NegiAkash890** [comment]
Hi Deepak, that's nice you can start by setting up the project with help of README. Let me know if you face any issue.

**Comment by Deepak-Kumar201** [comment]
Sir, I have to change text area of code to editable div to apply the feature of modern text editor like color full text and auto completion can I do?

**Comment by NegiAkash890** [comment]
Sure this can be done !

**Comment by NegiAkash890** [comment]
> Sir, I have to change text area of code to editable div to apply the feature of modern text editor like color full text and auto completion can I do?

Any updates ?

**Comment by Deepak-Kumar201** [comment]
Sorry sir, I cann't procced for now because of my end semester exams. Can I start after that

**Comment by NegiAkash890** [comment]
Ok, no problem I am closing this issue. You can open a new one whenever you feel like ;)
