### ISSUE TITLE
Auto-suggestion support with each language

### ISSUE THREAD

**Issue by Rishi-121** [NegiAkash890/editor-frontend#32]
@NegiAkash890 

Assign me with this issue. I will add auto-suggestion support with each language.

**Comment by NegiAkash890** [comment]
> @NegiAkash890
> 
> Assign me with this issue. I will add auto-suggestion support with each language.

Ok! Go ahead

**Comment by NegiAkash890** [comment]
any updates ?

**Comment by Rishi-121** [comment]
Busy with due some personal work.

Will do a PR after 4th of January.

@NegiAkash890

**Comment by aakankshabhende** [comment]
Any updates? @Rishi-121
