### ISSUE TITLE
Data Input should not be separate

### ISSUE THREAD

**Issue by kumar-tushar** [NegiAkash890/editor-frontend#34]
The data input should not be separate. 
The user will not be able to recognize when to enter the data if there is no line for example cout<<"Enter Number"
It should be combined in output so that user can perform step by step smoothly.

Here is the screenshot where I have not used cout before cin to make user understand as when to enter the data and due to which the output number is 0

![Screenshot (27)](https://user-images.githubusercontent.com/56949668/147399105-aeed591a-468f-4963-8659-8231948e38c4.png)

**Comment by aakankshabhende** [comment]
So what you want to add? @kumar-tushar

**Comment by anugoyal998** [comment]
> The data input should not be separate. The user will not be able to recognize when to enter the data if there is no line for example cout<<"Enter Number" It should be combined in output so that user can perform step by step smoothly.
> 
> Here is the screenshot where I have not used cout before cin to make user understand as when to enter the data and due to which the output number is 0
> 
> ![Screenshot (27)](https://user-images.githubusercontent.com/56949668/147399105-aeed591a-468f-4963-8659-8231948e38c4.png)

@kumar-tushar what the bug you are getting?

**Comment by kumar-tushar** [comment]
Actually, I am a project mentor but not currently added in this repo but added in excel sheet.
