### ISSUE TITLE
Adding some boilerplate code

### ISSUE THREAD

**Issue by developer-diganta** [NegiAkash890/editor-frontend#4]
The text area can have a default value depending on the language selected. Like for c++, the initial display may be :
#include<bits/stdc++.h>
using namespace std;
int main(){
    //Input the code here
}
If this is a valid issue, I can work on it.

**Comment by NegiAkash890** [comment]
Hi @developer-diganta you can work on it. I think project might already have some logic to handle this but its was not implemented due to some reason. Let me know if you face any issue.

**Comment by developer-diganta** [comment]
Yes I think we can combine both together.. Also another thing is we can introduce more stuff like account etc. and then redux becomes helpful...
