### ISSUE TITLE
Installation steps to setup locally

### ISSUE THREAD

**Issue by rushikeshadhav** [NegiAkash890/editor-frontend#9]
Steps to install locally must be added such as

How to clone
create new branch
make changes
commit
push your code

**Comment by NegiAkash890** [comment]
> Steps to install locally must be added such as
> 
> How to clone create new branch make changes commit push your code

Yes we can updated README for that

**Comment by rushikeshadhav** [comment]
Ok working on it 👍

**Comment by aakankshabhende** [comment]
Any updates? @rushikeshadhav

**Comment by NegiAkash890** [comment]
Closing this issue as @rushikeshadhav himself created a PR for the same previously which was merged into the main branch.
